% ================================================================
% NETRASURAKSHA MASTER HUB
% Government Census Radar + Model-Based XAI
% MATLAB R2026a
% ================================================================
%
% Save as:
%   NetraSuraksha_Master.m
%
% Required:
%   - Deep Learning Toolbox
%   - Image Processing Toolbox
%   - netrasuraksha_matlab_binary_95plus.mat
%
% NOTE:
%   Portal 3 uses Grad-CAM from the trained classifier.
%   Portal 4 maintains an in-session screening census by district.
%   Counts are based only on scans that pass image QC and complete
%   AI inference successfully.
% ================================================================

clc;
clear;
close all;

% ================================================================
% APPLICATION STATE
% ================================================================

app = uifigure( ...
    'Name', 'NetraSuraksha: Rural Vision Bridge', ...
    'Position', [80 40 1320 820], ...
    'Color', [0.07 0.07 0.08]);

app.UserData = struct( ...
    'PatientScanned', false, ...
    'IsReferable', false, ...
    'Name', '', ...
    'Age', '', ...
    'Sugar', '', ...
    'District', '', ...
    'Phone', '', ...
    'Img', [], ...
    'Verdict', '', ...
    'Confidence', 0, ...
    'GlareRatio', 0, ...
    'LargestGlareRatio', 0, ...
    'FocusScore', 0, ...
    'GradCAM', [], ...
    'GradCAMFeatureLayer', 'activation_49_relu', ...
    'GradCAMClassIndex', 1, ...
    'GradCAMArea', 0, ...
    'XAINet', [], ...
    'CensusTable', [], ...
    'TotalScannedLabel', [], ...
    'ReferableLabel', [], ...
    'NonReferableLabel', [], ...
    'ReferralRateLabel', [], ...
    'GovAx', [], ...
    'RegionDrop', [], ...
    'RegionDetailArea', [], ...
    'ScanRegistry', repmat(emptyScanRecord(), 0, 1));

% ================================================================
% TABS
% ================================================================

tg = uitabgroup(app, ...
    'Position', [10 10 1300 800]);

% ================================================================
% TAB 1 - FRONTLINE TRIAGE
% ================================================================

t1 = uitab(tg, ...
    'Title', 'Portal 1: Frontline Triage', ...
    'BackgroundColor', [0.10 0.10 0.12]);

intakePnl = uipanel(t1, ...
    'Position', [20 120 320 620], ...
    'BackgroundColor', [0.15 0.15 0.18], ...
    'ForegroundColor', 'w', ...
    'Title', 'STEP 1: PATIENT VITALS', ...
    'FontWeight', 'bold');

uilabel(intakePnl, ...
    'Text', 'Full Name:', ...
    'Position', [15 550 110 22], ...
    'FontColor', 'w');

ui.name = uieditfield(intakePnl, 'text', ...
    'Position', [15 525 280 25], ...
    'Value', 'Dev');

uilabel(intakePnl, ...
    'Text', 'Age:', ...
    'Position', [15 485 100 22], ...
    'FontColor', 'w');

ui.age = uieditfield(intakePnl, 'numeric', ...
    'Position', [15 460 130 25], ...
    'Value', 55);

uilabel(intakePnl, ...
    'Text', 'Random Blood Sugar (RBS):', ...
    'Position', [15 425 200 22], ...
    'FontColor', 'w');

ui.sugar = uieditfield(intakePnl, 'numeric', ...
    'Position', [15 400 280 25], ...
    'Value', 210);

uilabel(intakePnl, ...
    'Text', 'District / Region:', ...
    'Position', [15 365 200 22], ...
    'FontColor', 'w');

ui.district = uidropdown(intakePnl, ...
    'Items', {'Coimbatore', 'Madurai', 'Chennai', 'Salem', 'Trichy'}, ...
    'Position', [15 340 280 25], ...
    'Value', 'Coimbatore');

uilabel(intakePnl, ...
    'Text', 'Phone Number:', ...
    'Position', [15 305 200 22], ...
    'FontColor', 'w');

ui.phone = uieditfield(intakePnl, 'text', ...
    'Position', [15 280 280 25], ...
    'Value', '9876543210');

qcInfo = uilabel(intakePnl, ...
    'Text', { ...
    'IMAGE QUALITY GATES', ...
    '• Eye usability', ...
    '• Flash / glare detection', ...
    '• Blur / focus check', ...
    'Only valid scans enter the AI model.'}, ...
    'Position', [15 85 285 160], ...
    'FontColor', [0.75 0.85 0.95], ...
    'FontSize', 12);

scanPnl = uipanel(t1, ...
    'Position', [360 120 930 620], ...
    'BackgroundColor', [0.12 0.12 0.14], ...
    'ForegroundColor', 'w', ...
    'Title', 'STEP 2: EDGE-AI DIAGNOSTICS', ...
    'FontWeight', 'bold');

ax1_raw = uiaxes(scanPnl, ...
    'Position', [20 170 420 400]);
title(ax1_raw, 'Raw Capture', 'Color', 'w');

ax1_clahe = uiaxes(scanPnl, ...
    'Position', [480 170 420 400]);
title(ax1_clahe, 'CLAHE Enhanced', 'Color', 'w');

resLabel = uilabel(scanPnl, ...
    'Text', 'Awaiting Patient Intake & Capture...', ...
    'Position', [20 90 880 55], ...
    'FontSize', 20, ...
    'FontWeight', 'bold', ...
    'FontColor', [0.6 0.6 0.6], ...
    'HorizontalAlignment', 'center');

uibutton(t1, ...
    'Text', 'CAPTURE SCAN & RUN REAL INFERENCE', ...
    'Position', [360 40 930 60], ...
    'BackgroundColor', [0 0.4 0.8], ...
    'FontColor', 'w', ...
    'FontSize', 16, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(btn,event) ...
        runPortal1(app, ui, ax1_raw, ax1_clahe, resLabel));

% ================================================================
% TAB 2 - PATIENT ALERTS
% ================================================================

t2 = uitab(tg, ...
    'Title', 'Portal 2: Patient Alerts', ...
    'BackgroundColor', [0.10 0.10 0.12]);

phonePnl = uipanel(t2, ...
    'Position', [450 120 420 570], ...
    'BackgroundColor', [0.05 0.05 0.05], ...
    'BorderType', 'line', ...
    'HighlightColor', [0.3 0.3 0.3], ...
    'Title', 'PATIENT ALERT GATEWAY', ...
    'ForegroundColor', 'w', ...
    'FontWeight', 'bold');

msgArea = uitextarea(phonePnl, ...
    'Position', [15 15 390 520], ...
    'Editable', 'off', ...
    'FontSize', 14, ...
    'BackgroundColor', [0.10 0.10 0.10], ...
    'FontColor', [0.9 0.9 0.9]);

uibutton(t2, ...
    'Text', 'GENERATE ROUTING ALERT', ...
    'Position', [450 40 420 50], ...
    'BackgroundColor', [0 0.6 0], ...
    'FontColor', 'w', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(btn,event) ...
        runPortal2(app, msgArea));

% ================================================================
% TAB 3 - SPECIALIST / EXPLAINABLE AI
% ================================================================

t3 = uitab(tg, ...
    'Title', 'Portal 3: Specialist XAI', ...
    'BackgroundColor', [0.10 0.10 0.12]);

repPnl = uipanel(t3, ...
    'Position', [20 100 380 640], ...
    'BackgroundColor', [0.15 0.15 0.18], ...
    'ForegroundColor', 'w', ...
    'Title', 'AI EXPLANATION SUMMARY', ...
    'FontWeight', 'bold');

repArea = uitextarea(repPnl, ...
    'Position', [15 15 350 600], ...
    'Editable', 'off', ...
    'FontSize', 12.5, ...
    'BackgroundColor', [0.08 0.08 0.09], ...
    'FontColor', [0.8 0.95 0.85], ...
    'FontWeight', 'bold');

dashPnl = uipanel(t3, ...
    'Position', [420 100 870 640], ...
    'BackgroundColor', [0.12 0.12 0.14], ...
    'ForegroundColor', 'w', ...
    'Title', 'MODEL-BASED GRAD-CAM EXPLAINABILITY', ...
    'FontWeight', 'bold');

ax3_raw = uiaxes(dashPnl, ...
    'Position', [20 135 390 440]);
title(ax3_raw, 'Patient Eye', 'Color', 'w');

ax3_cam = uiaxes(dashPnl, ...
    'Position', [450 135 390 440]);
title(ax3_cam, 'Grad-CAM: Model Attention', 'Color', 'w');

uibutton(t3, ...
    'Text', 'GENERATE AI EXPLANATION', ...
    'Position', [20 35 380 50], ...
    'BackgroundColor', [0.2 0.45 0.8], ...
    'FontColor', 'w', ...
    'FontSize', 14, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(btn,event) ...
        runPortal3(app, ax3_raw, ax3_cam, repArea));

% ================================================================
% TAB 4 - GOVERNMENT CENSUS RADAR
% ================================================================

t4 = uitab(tg, ...
    'Title', 'Portal 4: Government Radar', ...
    'BackgroundColor', [0.08 0.09 0.11]);

% ---------------- TOP SUMMARY CARDS ----------------

card1 = uipanel(t4, ...
    'Position', [20 665 230 75], ...
    'BackgroundColor', [0.12 0.18 0.23], ...
    'Title', 'TOTAL SCANNED', ...
    'ForegroundColor', 'w', ...
    'FontWeight', 'bold');

totalScannedLabel = uilabel(card1, ...
    'Text', '0', ...
    'Position', [10 8 210 38], ...
    'FontSize', 25, ...
    'FontWeight', 'bold', ...
    'FontColor', 'w', ...
    'HorizontalAlignment', 'center');

card2 = uipanel(t4, ...
    'Position', [270 665 230 75], ...
    'BackgroundColor', [0.25 0.12 0.12], ...
    'Title', 'REFERABLE', ...
    'ForegroundColor', 'w', ...
    'FontWeight', 'bold');

referableLabel = uilabel(card2, ...
    'Text', '0', ...
    'Position', [10 8 210 38], ...
    'FontSize', 25, ...
    'FontWeight', 'bold', ...
    'FontColor', [1 0.55 0.45], ...
    'HorizontalAlignment', 'center');

card3 = uipanel(t4, ...
    'Position', [520 665 230 75], ...
    'BackgroundColor', [0.10 0.23 0.15], ...
    'Title', 'NON-REFERABLE', ...
    'ForegroundColor', 'w', ...
    'FontWeight', 'bold');

nonReferableLabel = uilabel(card3, ...
    'Text', '0', ...
    'Position', [10 8 210 38], ...
    'FontSize', 25, ...
    'FontWeight', 'bold', ...
    'FontColor', [0.45 1 0.65], ...
    'HorizontalAlignment', 'center');

card4 = uipanel(t4, ...
    'Position', [770 665 230 75], ...
    'BackgroundColor', [0.23 0.18 0.08], ...
    'Title', 'REFERRAL RATE', ...
    'ForegroundColor', 'w', ...
    'FontWeight', 'bold');

referralRateLabel = uilabel(card4, ...
    'Text', '0.0%', ...
    'Position', [10 8 210 38], ...
    'FontSize', 25, ...
    'FontWeight', 'bold', ...
    'FontColor', [1 0.8 0.35], ...
    'HorizontalAlignment', 'center');

% ---------------- MAP ----------------

mapPnl = uipanel(t4, ...
    'Position', [20 80 770 560], ...
    'BackgroundColor', [0.06 0.08 0.11], ...
    'ForegroundColor', 'w', ...
    'Title', 'REGIONAL SCREENING HEAT MAP', ...
    'FontWeight', 'bold');

govAx = uiaxes(mapPnl, ...
    'Position', [10 30 750 495], ...
    'Color', [0.04 0.05 0.07], ...
    'XColor', 'none', ...
    'YColor', 'none');

title(govAx, 'Referral-rate heat map | red = higher referral burden', ...
    'Color', 'w', 'FontSize', 13);

% ---------------- REGION DETAILS ----------------

detailPnl = uipanel(t4, ...
    'Position', [810 80 480 560], ...
    'BackgroundColor', [0.12 0.12 0.14], ...
    'ForegroundColor', 'w', ...
    'Title', 'REGIONAL CENSUS & SEVERITY', ...
    'FontWeight', 'bold');

uilabel(detailPnl, ...
    'Text', 'Select region:', ...
    'Position', [20 500 120 22], ...
    'FontColor', 'w');

regionDrop = uidropdown(detailPnl, ...
    'Items', {'Coimbatore', 'Madurai', 'Chennai', 'Salem', 'Trichy'}, ...
    'Position', [145 498 170 26], ...
    'Value', 'Coimbatore');

regionDetailArea = uitextarea(detailPnl, ...
    'Position', [20 305 435 170], ...
    'Editable', 'off', ...
    'FontSize', 13, ...
    'BackgroundColor', [0.08 0.08 0.09], ...
    'FontColor', [0.9 0.95 1]);

uibutton(detailPnl, ...
    'Text', 'VIEW REGION', ...
    'Position', [325 496 130 30], ...
    'BackgroundColor', [0.2 0.45 0.8], ...
    'FontColor', 'w', ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(btn,event) ...
        updateSelectedRegion(app, regionDrop, regionDetailArea));

censusTable = uitable(detailPnl, ...
    'Position', [20 75 435 210], ...
    'ColumnName', {'Region', 'Scanned', 'Referable', 'Non-Ref', 'Rate'}, ...
    'ColumnEditable', [false false false false false], ...
    'RowName', []);

severityLegend = uilabel(detailPnl, ...
    'Text', { ...
    'DEMO SEVERITY BANDS (based on referral rate)', ...
    '< 10%   LOW', ...
    '10-20%  MODERATE', ...
    '20-30%  HIGH', ...
    '> 30%   VERY HIGH'}, ...
    'Position', [20 5 435 65], ...
    'FontColor', [0.75 0.85 0.95], ...
    'FontSize', 11);

% ---------------- RESET ----------------

uibutton(t4, ...
    'Text', 'RESET SESSION CENSUS', ...
    'Position', [1030 665 260 75], ...
    'BackgroundColor', [0.35 0.12 0.12], ...
    'FontColor', 'w', ...
    'FontSize', 13, ...
    'FontWeight', 'bold', ...
    'ButtonPushedFcn', @(btn,event) ...
        resetCensus(app, censusTable, totalScannedLabel, ...
        referableLabel, nonReferableLabel, referralRateLabel, ...
        govAx, regionDetailArea, regionDrop));

% Store government dashboard handles so every successful scan can
% refresh the census automatically.
app.UserData.CensusTable = censusTable;
app.UserData.TotalScannedLabel = totalScannedLabel;
app.UserData.ReferableLabel = referableLabel;
app.UserData.NonReferableLabel = nonReferableLabel;
app.UserData.ReferralRateLabel = referralRateLabel;
app.UserData.GovAx = govAx;
app.UserData.RegionDrop = regionDrop;
app.UserData.RegionDetailArea = regionDetailArea;

% Initial government display
updateGovernmentPortal(app, censusTable, totalScannedLabel, ...
    referableLabel, nonReferableLabel, referralRateLabel, govAx);
updateSelectedRegion(app, regionDrop, regionDetailArea);

% ================================================================
% PORTAL 1 - QUALITY CONTROL + CLASSIFICATION
% ================================================================

function runPortal1(app, ui, ax_raw, ax_clahe, resLabel)

    % Reset previous scan state before a new attempt.
    app.UserData.PatientScanned = false;
    app.UserData.IsReferable = false;
    app.UserData.Img = [];
    app.UserData.Verdict = '';
    app.UserData.Confidence = 0;
    app.UserData.GradCAM = [];
    app.UserData.GradCAMArea = 0;

   [file, path] = uigetfile( ...
    {'*.png;*.jpg;*.jpeg;*.bmp', 'Retinal Images'}, ...
    'Select Retina Image');

if isequal(file, 0)
    figure(app);
    drawnow;
    return;
end

figure(app);
drawnow;

    try
        img = imread(fullfile(path, file));
    catch ME
        resLabel.Text = 'REJECTED: IMAGE COULD NOT BE READ';
        resLabel.FontColor = [1 0.2 0.2];
        warning('Image read failed: %s', ME.message);
        return;
    end

    % Make image RGB for a consistent model input.
    if ndims(img) == 2
        img = repmat(img, [1 1 3]);
    elseif size(img, 3) >= 3
        img = img(:, :, 1:3);
    else
        resLabel.Text = 'REJECTED: INVALID IMAGE FORMAT';
        resLabel.FontColor = [1 0.2 0.2];
        return;
    end

    imshow(img, 'Parent', ax_raw);
    axis(ax_raw, 'image');
    ax_raw.XTick = [];
    ax_raw.YTick = [];

    grayImg = rgb2gray(img);
    stdGray = imresize(grayImg, [512 512]);

    % ------------------------------------------------------------
    % IMAGE QUALITY GATE
    % ------------------------------------------------------------

    eyeMask = stdGray > 15;
    totalEyePixels = nnz(eyeMask);

    if totalEyePixels < 10000
        resLabel.Text = 'REJECTED: NO USABLE EYE DETECTED';
        resLabel.FontColor = [1 0.2 0.2];
        return;
    end

    % Strongly saturated reflection.
    glareMask = stdGray > 240;
    glareMask = bwareaopen(glareMask, 25);
    glareMask = glareMask & eyeMask;

    totalGlareRatio = nnz(glareMask) / totalEyePixels;

    % Largest connected glare component.
    cc = bwconncomp(glareMask);
    largestGlareRatio = 0;

    if cc.NumObjects > 0
        componentSizes = cellfun(@numel, cc.PixelIdxList);
        largestGlareRatio = max(componentSizes) / totalEyePixels;
    end

    % Broader bright artifact threshold for reflections that are not pure white.
    broadGlareMask = stdGray > 220;
    broadGlareMask = bwareaopen(broadGlareMask, 25);
    broadGlareMask = broadGlareMask & eyeMask;
    broadGlareRatio = nnz(broadGlareMask) / totalEyePixels;

    if totalGlareRatio > 0.020
        resLabel.Text = sprintf( ...
            'REJECTED: EXCESSIVE FLASH GLARE (%.2f%%)', ...
            totalGlareRatio * 100);
        resLabel.FontColor = [1 0.2 0.2];
        return;
    end

    if largestGlareRatio > 0.008
        resLabel.Text = sprintf( ...
            'REJECTED: LARGE FLASH REFLECTION (%.2f%%)', ...
            largestGlareRatio * 100);
        resLabel.FontColor = [1 0.2 0.2];
        return;
    end

    if broadGlareRatio > 0.040
        resLabel.Text = sprintf( ...
            'REJECTED: EXCESSIVE BRIGHT ARTIFACT (%.2f%%)', ...
            broadGlareRatio * 100);
        resLabel.FontColor = [1 0.2 0.2];
        return;
    end

    % ------------------------------------------------------------
    % FOCUS CHECK
    % ------------------------------------------------------------

    safeTissue = eyeMask & ...
        ~imdilate(glareMask, strel('disk', 5));

    lapImg = imfilter( ...
        double(stdGray), ...
        fspecial('laplacian', 0.2), ...
        'replicate');

    focusPixels = lapImg(safeTissue);

    if isempty(focusPixels)
        resLabel.Text = 'REJECTED: INSUFFICIENT USABLE TISSUE';
        resLabel.FontColor = [1 0.2 0.2];
        return;
    end

    focusScore = var(focusPixels);

    if focusScore < 15.0
        resLabel.Text = sprintf( ...
            'REJECTED: BLURRY IMAGE (Focus %.1f)', ...
            focusScore);
        resLabel.FontColor = [1 0.2 0.2];
        return;
    end

    % ------------------------------------------------------------
    % CLAHE VIEW
    % ------------------------------------------------------------

    claheEye = adapthisteq(grayImg, ...
        'NumTiles', [8 8], ...
        'ClipLimit', 0.02);

    imshow(claheEye, 'Parent', ax_clahe);
    axis(ax_clahe, 'image');
    ax_clahe.XTick = [];
    ax_clahe.YTick = [];

    app.UserData.GlareRatio = totalGlareRatio;
    app.UserData.LargestGlareRatio = largestGlareRatio;
    app.UserData.FocusScore = focusScore;

    resLabel.Text = 'QUALITY PASS - Processing trained AI model...';
    resLabel.FontColor = [0.3 0.7 1];
    drawnow;

    % ------------------------------------------------------------
    % LOAD TRAINED DAG NETWORK
    % ------------------------------------------------------------

    try
        modelFile = 'netrasuraksha_matlab_binary_95plus.mat';

        if ~isfile(modelFile)
            error('Model file "%s" was not found.', modelFile);
        end

        S = load(modelFile, 'trainedNet');
        trainedNet = S.trainedNet;

        if ~isa(trainedNet, 'DAGNetwork')
            error('Expected trainedNet to be a DAGNetwork. Found: %s', class(trainedNet));
        end

        imgResized = imresize(img, [224 224]);
        [pred, scores] = classify(trainedNet, imgResized);

        aiVerdict = string(pred);
        confidenceScore = max(scores(:)) * 100;

        % Keep the model available for Portal 3.
        app.UserData.XAINet = dag2dlnetwork(trainedNet);

        classNames = trainedNet.Layers(end).Classes;
        classIdx = find(strcmpi(string(classNames), aiVerdict), 1);

        if isempty(classIdx)
            error('Could not map AI prediction to the network class index.');
        end

        app.UserData.GradCAMClassIndex = classIdx;

    catch ME
        app.UserData.XAINet = [];
        resLabel.Text = 'ERROR: AI MODEL COULD NOT RUN';
        resLabel.FontColor = [1 0.4 0.2];
        warning('AI inference failed: %s', ME.message);
        return;
    end

    % ------------------------------------------------------------
    % STORE PATIENT RESULT
    % ------------------------------------------------------------

    app.UserData.Name = ui.name.Value;
    app.UserData.Age = num2str(ui.age.Value);
    app.UserData.Sugar = num2str(ui.sugar.Value);
    app.UserData.District = ui.district.Value;
    app.UserData.Phone = ui.phone.Value;
    app.UserData.Img = img;
    app.UserData.Verdict = aiVerdict;
    app.UserData.Confidence = confidenceScore;
    app.UserData.PatientScanned = true;

    v = strtrim(lower(aiVerdict));

    isHealthy = ...
        (v == "nonreferable") || ...
        (v == "non-referable") || ...
        (v == "normal") || ...
        (v == "no dr") || ...
        (v == "no_dr") || ...
        (v == "0");

    app.UserData.IsReferable = ~isHealthy;

    % ------------------------------------------------------------
    % ADD TO GOVERNMENT CENSUS REGISTRY
    % ------------------------------------------------------------

    newRecord = emptyScanRecord();
    newRecord.District = char(ui.district.Value);
    newRecord.Verdict = char(aiVerdict);
    newRecord.Confidence = confidenceScore;
    newRecord.IsReferable = app.UserData.IsReferable;

    registry = app.UserData.ScanRegistry;
    registry(end + 1) = newRecord;
    app.UserData.ScanRegistry = registry;

    % Refresh the government census immediately after every successful scan.
    if ~isempty(app.UserData.CensusTable)
        updateGovernmentPortal(app, ...
            app.UserData.CensusTable, ...
            app.UserData.TotalScannedLabel, ...
            app.UserData.ReferableLabel, ...
            app.UserData.NonReferableLabel, ...
            app.UserData.ReferralRateLabel, ...
            app.UserData.GovAx);

        updateSelectedRegion(app, ...
            app.UserData.RegionDrop, ...
            app.UserData.RegionDetailArea);
    end

    % ------------------------------------------------------------
    % FINAL STATUS
    % ------------------------------------------------------------

    if app.UserData.IsReferable
        resLabel.Text = sprintf( ...
            'QUALITY PASS | AI: %s | Confidence: %.1f%%', ...
            aiVerdict, confidenceScore);
        resLabel.FontColor = [1 0.6 0];
    else
        resLabel.Text = sprintf( ...
            'QUALITY PASS | AI: %s | Confidence: %.1f%%', ...
            aiVerdict, confidenceScore);
        resLabel.FontColor = [0 0.8 0];
    end

end

% ================================================================
% PORTAL 2 - PATIENT ALERT
% ================================================================

function runPortal2(app, msgArea)

    if ~app.UserData.PatientScanned
        msgArea.Value = { ...
            'ERROR: No valid patient scan is available.', ...
            '', ...
            'Run Portal 1 first.'};
        return;
    end

    if app.UserData.IsReferable
        msgArea.Value = { ...
            'NETRASURAKSHA ALERT', ...
            '', ...
            sprintf('Dear %s,', app.UserData.Name), ...
            '', ...
            'Your AI screening result is classified as referable.', ...
            '', ...
            'ACTION REQUIRED:', ...
            'Please visit an eye-care professional for confirmation.', ...
            '', ...
            sprintf('District: %s', app.UserData.District), ...
            sprintf('Phone: %s', app.UserData.Phone)};
    else
        msgArea.Value = { ...
            'NETRASURAKSHA UPDATE', ...
            '', ...
            sprintf('Dear %s,', app.UserData.Name), ...
            '', ...
            'Your AI screening result is classified as non-referable.', ...
            '', ...
            'Continue routine eye screening according to clinical guidance.'};
    end

end

% ================================================================
% PORTAL 3 - ACTUAL MODEL-BASED GRAD-CAM
% ================================================================

function runPortal3(app, ax_raw, ax_cam, repArea)

    if ~app.UserData.PatientScanned
        repArea.Value = { ...
            'ERROR: No valid patient scan found.', ...
            '', ...
            'Run Portal 1 first.'};
        return;
    end

    if isempty(app.UserData.XAINet)
        repArea.Value = { ...
            'ERROR: XAI network is not available.', ...
            '', ...
            'Run Portal 1 again so the trained model can be loaded.'};
        return;
    end

    img = app.UserData.Img;
    imshow(img, 'Parent', ax_raw);
    axis(ax_raw, 'image');
    ax_raw.XTick = [];
    ax_raw.YTick = [];

    try
        imgResized = imresize(img, [224 224]);

        % --------------------------------------------------------
        % TRUE GRAD-CAM FROM THE TRAINED NETWORK
        % --------------------------------------------------------
        scoreMap = gradCAM( ...
            app.UserData.XAINet, ...
            imgResized, ...
            app.UserData.GradCAMClassIndex, ...
            'FeatureLayer', app.UserData.GradCAMFeatureLayer);

        scoreMap = squeeze(scoreMap);
        scoreMap = mat2gray(scoreMap);
        scoreMap = imresize(scoreMap, [size(img,1) size(img,2)]);

        app.UserData.GradCAM = scoreMap;

        % High-attention region = thresholded Grad-CAM, not lesion segmentation.
        attentionMask = scoreMap >= 0.60;
        attentionMask = bwareaopen(attentionMask, 50);

        usableMask = rgb2gray(img) > 15;
        attentionMask = attentionMask & usableMask;

        if nnz(usableMask) > 0
            gradCAMArea = nnz(attentionMask) / nnz(usableMask) * 100;
        else
            gradCAMArea = 0;
        end

        app.UserData.GradCAMArea = gradCAMArea;

        % --------------------------------------------------------
        % DISPLAY GRAD-CAM OVERLAY
        % --------------------------------------------------------
        imshow(img, 'Parent', ax_cam);
        axis(ax_cam, 'image');
        ax_cam.XTick = [];
        ax_cam.YTick = [];
        hold(ax_cam, 'on');

        heatHandle = imagesc(ax_cam, scoreMap);
        colormap(ax_cam, jet(256));
        heatHandle.AlphaData = 0.50 * scoreMap;

        % Visual boundary of the strongest attention area.
        if any(attentionMask(:))
            contour(ax_cam, attentionMask, [1 1], ...
                'Color', 'w', 'LineWidth', 1.5);
        end

        colorbar(ax_cam);
        caxis(ax_cam, [0 1]);
        title(ax_cam, 'Grad-CAM: Stronger model influence', 'Color', 'w');
        hold(ax_cam, 'off');

        % --------------------------------------------------------
        % DOCTOR-FACING EXPLANATION
        % --------------------------------------------------------

        if app.UserData.IsReferable
            actionText = ...
                'Recommended next step: professional ophthalmic evaluation.';
        else
            actionText = ...
                'Recommended next step: routine follow-up according to clinical guidance.';
        end

        if app.UserData.Confidence >= 80
            confidenceText = 'High model confidence.';
        elseif app.UserData.Confidence >= 60
            confidenceText = 'Moderate model confidence.';
        else
            confidenceText = 'Lower model confidence; review the image carefully.';
        end

        reportLines = { ...
            sprintf('PATIENT: %s', app.UserData.Name), ...
            sprintf('AGE: %s | RBS: %s', app.UserData.Age, app.UserData.Sugar), ...
            sprintf('REGION: %s', app.UserData.District), ...
            '', ...
            sprintf('AI DIAGNOSIS: %s', upper(app.UserData.Verdict)), ...
            sprintf('MODEL CONFIDENCE: %.1f%%', app.UserData.Confidence), ...
            confidenceText, ...
            '', ...
            '--- AI EXPLANATION ---', ...
            'The trained classifier produced the diagnosis shown above.', ...
            'Grad-CAM identifies image regions that contributed strongly', ...
            'to the predicted class score.', ...
            '', ...
            sprintf('HIGHLIGHTED ATTENTION AREA: %.2f%%', gradCAMArea), ...
            '', ...
            '--- HOW TO READ THE MAP ---', ...
            'Red / yellow = stronger model contribution.', ...
            'Blue / dark = weaker model contribution.', ...
            '', ...
            '--- IMPORTANT XAI NOTE ---', ...
            'This is a model-attention map, not a pixel-perfect lesion', ...
            'segmentation. It shows where the classifier was influenced.', ...
            '', ...
            '--- ACTION ---', ...
            actionText};

        repArea.Value = reportLines;

    catch ME
        app.UserData.GradCAM = [];
        app.UserData.GradCAMArea = 0;

        repArea.Value = { ...
            'ERROR: GRAD-CAM COULD NOT BE GENERATED.', ...
            '', ...
            'The classification result remains available in Portal 1.', ...
            '', ...
            sprintf('Technical message: %s', ME.message)};

        warning('Grad-CAM failed: %s', ME.message);
    end

end

% ================================================================
% GOVERNMENT PORTAL UPDATE
% ================================================================

function updateGovernmentPortal(app, censusTable, ...
    totalScannedLabel, referableLabel, nonReferableLabel, ...
    referralRateLabel, govAx)

    districts = {'Coimbatore', 'Madurai', 'Chennai', 'Salem', 'Trichy'};

    scanned = zeros(numel(districts), 1);
    referable = zeros(numel(districts), 1);
    nonReferable = zeros(numel(districts), 1);

    registry = app.UserData.ScanRegistry;

    for i = 1:numel(districts)
        districtMask = strcmpi( ...
            {registry.District}, districts{i});

        districtRecords = registry(districtMask);

        scanned(i) = numel(districtRecords);

        if ~isempty(districtRecords)
            referable(i) = sum([districtRecords.IsReferable]);
            nonReferable(i) = scanned(i) - referable(i);
        end
    end

    totalScanned = sum(scanned);
    totalReferable = sum(referable);
    totalNonReferable = sum(nonReferable);

    if totalScanned > 0
        overallReferralRate = totalReferable / totalScanned * 100;
    else
        overallReferralRate = 0;
    end

    totalScannedLabel.Text = num2str(totalScanned);
    referableLabel.Text = num2str(totalReferable);
    nonReferableLabel.Text = num2str(totalNonReferable);
    referralRateLabel.Text = sprintf('%.1f%%', overallReferralRate);

    % Table data.
    rates = zeros(numel(districts), 1);
    for i = 1:numel(districts)
        if scanned(i) > 0
            rates(i) = referable(i) / scanned(i) * 100;
        end
    end

    tableData = cell(numel(districts), 5);

    for i = 1:numel(districts)
        tableData{i,1} = districts{i};
        tableData{i,2} = scanned(i);
        tableData{i,3} = referable(i);
        tableData{i,4} = nonReferable(i);
        tableData{i,5} = sprintf('%.1f%%', rates(i));
    end

    censusTable.Data = tableData;

    % ------------------------------------------------------------
    % REGIONAL HEAT MAP
    % ------------------------------------------------------------

    lats = [ ...
        11.0168 ... % Coimbatore
        9.9252  ... % Madurai
        13.0827 ... % Chennai
        11.6643 ... % Salem
        10.7905];   % Trichy

    lons = [ ...
        76.9558 ...
        78.1198 ...
        80.2707 ...
        78.1460 ...
        78.7047];

    cla(govAx);
    hold(govAx, 'on');

    % Approximate Tamil Nadu outline for the demo dashboard.
    tn_lon = [76.0 77.0 78.0 79.5 80.3 79.8 79.0 78.0 77.0 76.0];
    tn_lat = [11.5 13.0 13.5 13.5 13.0 10.5 9.0 8.0 9.5 11.5];

    fill(govAx, tn_lon, tn_lat, [0.12 0.14 0.18], ...
        'EdgeColor', [0 0.7 1], ...
        'LineWidth', 1.5);

    % Marker size reflects screening volume; color reflects referral rate.
    markerSizes = 160 + 70 .* sqrt(double(scanned));

    scatter(govAx, lons, lats, markerSizes, rates, ...
        'filled', ...
        'MarkerEdgeColor', 'w', ...
        'LineWidth', 0.8);

    colormap(govAx, hot(256));
    caxis(govAx, [0 max(30, max(rates) + 1)]);
    cb = colorbar(govAx);
    cb.Color = 'w';
    cb.Label.String = 'Referral rate (%)';
    cb.Label.Color = 'w';

    text(govAx, lons, lats - 0.22, districts, ...
        'Color', 'w', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 10, ...
        'FontWeight', 'bold');

    % Add screening count above each location.
    for i = 1:numel(districts)
        text(govAx, lons(i), lats(i) + 0.22, ...
            sprintf('N=%d | %.1f%%', scanned(i), rates(i)), ...
            'Color', [0.9 0.9 0.9], ...
            'HorizontalAlignment', 'center', ...
            'FontSize', 8);
    end

    govAx.XLim = [75.0 81.5];
    govAx.YLim = [7.5 14.0];
    govAx.XTick = [];
    govAx.YTick = [];
    axis(govAx, 'equal');

    hold(govAx, 'off');

end

% ================================================================
% SELECTED REGION DETAILS
% ================================================================

function updateSelectedRegion(app, regionDrop, regionDetailArea)

    selectedRegion = char(regionDrop.Value);
    registry = app.UserData.ScanRegistry;

    mask = strcmpi({registry.District}, selectedRegion);
    records = registry(mask);

    scanned = numel(records);

    if scanned > 0
        referable = sum([records.IsReferable]);
    else
        referable = 0;
    end

    nonReferable = scanned - referable;

    if scanned > 0
        referralRate = referable / scanned * 100;
    else
        referralRate = 0;
    end

    severity = getSeverityBand(referralRate);

    regionDetailArea.Value = { ...
        sprintf('REGION: %s', selectedRegion), ...
        '', ...
        sprintf('Total scanned: %d', scanned), ...
        sprintf('Referable: %d', referable), ...
        sprintf('Non-referable: %d', nonReferable), ...
        sprintf('Referral rate: %.1f%%', referralRate), ...
        '', ...
        sprintf('SEVERITY BAND: %s', severity), ...
        '', ...
        'Interpretation:', ...
        'This demo heat map summarizes the proportion of', ...
        'successfully screened cases classified as referable.', ...
        '', ...
        'These severity bands are demonstration thresholds,', ...
        'not clinical or epidemiological standards.'};

end

% ================================================================
% RESET CENSUS
% ================================================================

function resetCensus(app, censusTable, totalScannedLabel, ...
    referableLabel, nonReferableLabel, referralRateLabel, ...
    govAx, regionDetailArea, regionDrop)

    answer = uiconfirm(app, ...
        'Clear all screening counts from this session?', ...
        'Reset Government Census', ...
        'Options', {'Reset', 'Cancel'}, ...
        'DefaultOption', 2, ...
        'CancelOption', 2);

    if strcmp(answer, 'Reset')
        app.UserData.ScanRegistry = repmat(emptyScanRecord(), 0, 1);

        updateGovernmentPortal(app, censusTable, totalScannedLabel, ...
            referableLabel, nonReferableLabel, referralRateLabel, govAx);

        regionDetailArea.Value = {'Select a region and click VIEW REGION.'};
        regionDrop.Value = 'Coimbatore';
    end

end

% ================================================================
% SEVERITY BAND HELPER
% ================================================================

function severity = getSeverityBand(referralRate)

    if referralRate < 10
        severity = 'LOW';
    elseif referralRate < 20
        severity = 'MODERATE';
    elseif referralRate < 30
        severity = 'HIGH';
    else
        severity = 'VERY HIGH';
    end

end

% ================================================================
% EMPTY REGISTRY RECORD
% ================================================================

function record = emptyScanRecord()

    record = struct( ...
        'District', '', ...
        'Verdict', '', ...
        'Confidence', 0, ...
        'IsReferable', false);

end
